//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.PlayersInTeams = new HashSet<PlayersInTeam>();
        }
    
        public System.Guid PlayerID { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public string Surname { get; set; }
        public int CountryID { get; set; }
        public int Age { get; set; }
        public double Rating { get; set; }
        public int PlayedMaps { get; set; }
        public int PlayedRounds { get; set; }
        public System.Guid RoleID { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayersInTeam> PlayersInTeams { get; set; }
    }
}
