//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Information_System_for_eSport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set
    {
        public System.Guid SetID { get; set; }
        public System.Guid MatchID { get; set; }
        public System.Guid MapID { get; set; }
        public int FirstTeam { get; set; }
        public int SecondTeam { get; set; }
    
        public virtual Map Map { get; set; }
        public virtual MatchesInTournament MatchesInTournament { get; set; }
    }
}
